version: '3.7'

services:
  nosql:
    image: mongo:latest
    container_name: mongo-instaclone
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      # Windows
      # - mongo-instaclone-data:/data/db
      # *nix
      - ./mongo_data:/data/db
  instaclone:
    build: .
    container_name: instaclone
    ports:
      - 3000:3000
    volumes:
      # windows
      # - .\code:/code
      # *nix
      - ./code:/code
    working_dir: /code
    command: sh -c "yarn && yarn start"
    depends_on:
      - nosql
networks:
  default:
    name: instaclone-net
# WARNING: Windows Users Only
# volumes:
#   mongo-instaclone-data:
#     driver: local